#!/bin/sh

# ash : Contains oftenly used shell functions
# @author: Hubert The Elephant <hubert@creakiwi.com>
# @author: Alexandre ANDRE <alexandre@creakiwi.com>

################
# REQUIREMENTS #
################

# usage: check_bin binary
check_bin()
{
	if [ -z `which ${1}` ]
	then
		exit_error 1 "Unable to find required binary \"${1}\""
	fi
}

# usage: check_bins
check_bins()
{
	check_bin "awk"
}

################
# EXIT METHODS #
################

# usage: exit_error [error_code [error_msg]]
exit_error()
{
	if [ ${#} -eq 2 ]
	then
		echo ${2} >&2
	fi

	if [ $# -ge 1 ]
	then
		exit ${1}
	else
		exit 1
	fi
}

# usage: exit_success
exit_success()
{
	exit 0
}

#################
# FILES METHODS #
#################

# usage: file_exists file
file_exists()
{
	file_exists_r=0
	if [ -e ${1} ]
	then
		file_exits_r=1
	fi
}

# usage: is_file file
is_file()
{
	is_file_r=0
	if [ -f ${1} ]
	then
		is_file_r=1
	fi
}

# usage: is_dir directory
is_dir()
{
	is_dir_r=0
	if [ -d ${1} ]
	then
		is_dir_r=1
	fi
}

# usage: is_writable path
is_writable()
{
	is_writable_r=0
	if [ -w ${1} ]
	then
		is_writable_r=1
	fi
}

# usage: is_readable path
is_readable()
{
	is_readable_r=0
	if [ -r ${1} ]
	then
		is_readable_r=1
	fi
}

##################
# STRING METHODS #
##################

# usage: lowercase string
lowercase()
{
	lowercase_r=`echo ${1} | awk '{ print tolower($0) }'`
}

# usage: str_replace occurrence substitution string [max_occurrences]
str_replace()
{
    if [ ${#} -eq 4 ]
    then
        str_replace_r=${3}
        i=0
        while [ ${i} -lt ${4} ]
        do
            str_replace_r=`echo ${str_replace_r} | awk '{ sub(/'${1}'/, "'${2}'"); print }'`
            i=`expr ${i} + 1`
        done
    else
        str_replace_r=`echo ${3} | awk '{ gsub(/'${1}'/, "'${2}'"); print }'`
    fi
}

check_bins

argc=${#}
